### ISSUE TITLE
BatchGetSymbols

### ISSUE THREAD

**Issue by DanTheRedMan** [msperlin/BatchGetSymbols#5]
Hello,

My personal R website went down in the last few days, and I narrowed it down to the BatchGetSymbols package.  

When trying to run the package, an error message.  Below is the code and the error message.   Any suggestions?

Code:

library(BatchGetSymbols)
df.SP500 <- GetSP500Stocks()
print(df.SP500)

Error:

'names' attribute [8] must be the same length as the vector [2]

**Comment by shosaco** [comment]
Solution: Get the 2nd table instead of the first on on Wikipedia Page. Issue is that they added a table noting external references, so you Function must now aim for the second table.

Answer implelented: [https://stackoverflow.com/a/54390523/6498638](https://stackoverflow.com/a/54390523/6498638)

Note this is still a very shaky solution, because if wikipedia removes the first table, your argument needs to change again.

**Comment by msperlin** [comment]
Thanks Shosaco. That should fix it.
