### ISSUE TITLE
Missing dates for BTC?

### ISSUE THREAD

**Issue by msperlin** [msperlin/BatchGetSymbols#7]
`library(BatchGetSymbols)

titoli <- c('BTC-EUR') 
data.inizio <- "2018-01-01"
data.fine <- "2019-01-01"

lista <- BatchGetSymbols(tickers = titoli,
                         first.date = data.inizio,
                         last.date = data.fine,
                         do.cache = FALSE)

`

**Comment by zecaclasher** [comment]
The error comes from the file **Utils.R**,  **line 71**, inside the function **get.clean.data**.

After the call to **quantmod::getSymbols** (line **47**), it happens that for this specific ticker **BTC-EUR** (same issue with **BTC-USD**), **quantmod** returns an **xts** object with indexes consisting of dates plus an X (e.g. **X2011.08.26**). This is the reason why one gets an error message from the call to **as.Date** (line **71**) because the date format is wrong.

The issue comes from the data provider, i.e., **Yahoo**. I could not find a reason for this issue from Yahoo but it seems that it rarely happens, i.e, only a few specific tickers have this issue.

One could use the ticker **BTCUSD=X** for the Bitcoin / USD data which the data is fine but I could not find an alternative for the **BTC-EUR** data.

See [https://stackoverflow.com/questions/48850027/quantmod-chartseries-not-working-with-some-stocks] for another explanation.

**Comment by zecaclasher** [comment]
Just found the actual issue.

The **BTC-EUR** data from Yahoo has duplicates which leads **xts()** to create an index with an **X** in front of the dates.

I have created a workaround for this issue. I tested it and found no side effects.

A pull-request is going to be created soon so you can check it.

`df.out <- as.data.frame(df.out[!duplicated(zoo::index(df.out))])`

**Comment by msperlin** [comment]
Thank you again zecaclasher. Really apreciate the help! I'll check the pull-request.
